/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FinishedAuctionsRouteImport } from './routes/finished-auctions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UniqueBidsIdRouteImport } from './routes/unique-bids.$id'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUniqueBidsRouteImport } from './routes/admin/unique-bids'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminSupportFaqsRouteImport } from './routes/admin/support-faqs'
import { Route as AdminSupportChatsRouteImport } from './routes/admin/support-chats'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminRobotsRouteImport } from './routes/admin/robots'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPhrasesRouteImport } from './routes/admin/phrases'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminClaimsRouteImport } from './routes/admin/claims'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAuctionsRouteImport } from './routes/admin/auctions'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedAuctionsRoute = FinishedAuctionsRouteImport.update({
  id: '/finished-auctions',
  path: '/finished-auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UniqueBidsIdRoute = UniqueBidsIdRouteImport.update({
  id: '/unique-bids/$id',
  path: '/unique-bids/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUniqueBidsRoute = AdminUniqueBidsRouteImport.update({
  id: '/unique-bids',
  path: '/unique-bids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportFaqsRoute = AdminSupportFaqsRouteImport.update({
  id: '/support-faqs',
  path: '/support-faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportChatsRoute = AdminSupportChatsRouteImport.update({
  id: '/support-chats',
  path: '/support-chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRobotsRoute = AdminRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhrasesRoute = AdminPhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/finished-auctions': typeof FinishedAuctionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-chats': typeof AdminSupportChatsRoute
  '/admin/support-faqs': typeof AdminSupportFaqsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/unique-bids': typeof AdminUniqueBidsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/unique-bids/$id': typeof UniqueBidsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finished-auctions': typeof FinishedAuctionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-chats': typeof AdminSupportChatsRoute
  '/admin/support-faqs': typeof AdminSupportFaqsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/unique-bids': typeof AdminUniqueBidsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/unique-bids/$id': typeof UniqueBidsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/finished-auctions': typeof FinishedAuctionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support-chats': typeof AdminSupportChatsRoute
  '/admin/support-faqs': typeof AdminSupportFaqsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/unique-bids': typeof AdminUniqueBidsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/unique-bids/$id': typeof UniqueBidsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/finished-auctions'
    | '/how-it-works'
    | '/packages'
    | '/privacy-policy'
    | '/profile'
    | '/ranking'
    | '/terms-of-use'
    | '/admin/auctions'
    | '/admin/banners'
    | '/admin/claims'
    | '/admin/packages'
    | '/admin/phrases'
    | '/admin/products'
    | '/admin/robots'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support-chats'
    | '/admin/support-faqs'
    | '/admin/testimonials'
    | '/admin/unique-bids'
    | '/admin/users'
    | '/auctions/$id'
    | '/sitemap/xml'
    | '/unique-bids/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finished-auctions'
    | '/how-it-works'
    | '/packages'
    | '/privacy-policy'
    | '/profile'
    | '/ranking'
    | '/terms-of-use'
    | '/admin/auctions'
    | '/admin/banners'
    | '/admin/claims'
    | '/admin/packages'
    | '/admin/phrases'
    | '/admin/products'
    | '/admin/robots'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support-chats'
    | '/admin/support-faqs'
    | '/admin/testimonials'
    | '/admin/unique-bids'
    | '/admin/users'
    | '/auctions/$id'
    | '/sitemap/xml'
    | '/unique-bids/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/finished-auctions'
    | '/how-it-works'
    | '/packages'
    | '/privacy-policy'
    | '/profile'
    | '/ranking'
    | '/terms-of-use'
    | '/admin/auctions'
    | '/admin/banners'
    | '/admin/claims'
    | '/admin/packages'
    | '/admin/phrases'
    | '/admin/products'
    | '/admin/robots'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support-chats'
    | '/admin/support-faqs'
    | '/admin/testimonials'
    | '/admin/unique-bids'
    | '/admin/users'
    | '/auctions/$id'
    | '/sitemap/xml'
    | '/unique-bids/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FinishedAuctionsRoute: typeof FinishedAuctionsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  UniqueBidsIdRoute: typeof UniqueBidsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished-auctions': {
      id: '/finished-auctions'
      path: '/finished-auctions'
      fullPath: '/finished-auctions'
      preLoaderRoute: typeof FinishedAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/unique-bids/$id': {
      id: '/unique-bids/$id'
      path: '/unique-bids/$id'
      fullPath: '/unique-bids/$id'
      preLoaderRoute: typeof UniqueBidsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unique-bids': {
      id: '/admin/unique-bids'
      path: '/unique-bids'
      fullPath: '/admin/unique-bids'
      preLoaderRoute: typeof AdminUniqueBidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-faqs': {
      id: '/admin/support-faqs'
      path: '/support-faqs'
      fullPath: '/admin/support-faqs'
      preLoaderRoute: typeof AdminSupportFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-chats': {
      id: '/admin/support-chats'
      path: '/support-chats'
      fullPath: '/admin/support-chats'
      preLoaderRoute: typeof AdminSupportChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/robots': {
      id: '/admin/robots'
      path: '/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AdminRobotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/phrases': {
      id: '/admin/phrases'
      path: '/phrases'
      fullPath: '/admin/phrases'
      preLoaderRoute: typeof AdminPhrasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPhrasesRoute: typeof AdminPhrasesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRobotsRoute: typeof AdminRobotsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportChatsRoute: typeof AdminSupportChatsRoute
  AdminSupportFaqsRoute: typeof AdminSupportFaqsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUniqueBidsRoute: typeof AdminUniqueBidsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPhrasesRoute: AdminPhrasesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRobotsRoute: AdminRobotsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportChatsRoute: AdminSupportChatsRoute,
  AdminSupportFaqsRoute: AdminSupportFaqsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUniqueBidsRoute: AdminUniqueBidsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FinishedAuctionsRoute: FinishedAuctionsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  UniqueBidsIdRoute: UniqueBidsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
