ALTER TABLE public.site_settings 
ADD COLUMN IF NOT EXISTS logo_height_mobile INTEGER DEFAULT 32,
ADD COLUMN IF NOT EXISTS logo_padding_x INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS logo_padding_y INTEGER DEFAULT 0;